"""empty message

Revision ID: 13409abebe8c
Revises: ffad1511abd1
Create Date: 2016-03-12 12:38:41.430964

"""

# revision identifiers, used by Alembic.
revision = '13409abebe8c'
down_revision = 'ffad1511abd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebao_leave',
    sa.Column('apply_id', sa.Integer(), nullable=True),
    sa.Column('apply_name', sa.String(length=64), nullable=False),
    sa.Column('apply_reason', sa.String(length=64), nullable=True),
    sa.Column('current_version', sa.String(length=64), nullable=True),
    sa.Column('week_number', sa.String(length=64), nullable=False),
    sa.Column('apply_date', sa.DateTime(), nullable=True),
    sa.Column('overtime_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('apply_name', 'week_number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebao_leave')
    ### end Alembic commands ###
