"""empty message

Revision ID: 2eb7cddf18ae
Revises: 42b333953c25
Create Date: 2016-03-08 17:02:50.698242

"""

# revision identifiers, used by Alembic.
revision = '2eb7cddf18ae'
down_revision = '42b333953c25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personal_gravatar', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personal_gravatar')
    ### end Alembic commands ###
