"""empty message

Revision ID: 7fd8e3e209a8
Revises: dddcc66b75ef
Create Date: 2016-02-25 19:30:43.889949

"""

# revision identifiers, used by Alembic.
revision = '7fd8e3e209a8'
down_revision = 'dddcc66b75ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
