"""empty message

Revision ID: 90b5d9ef4ef2
Revises: df2ed3a8ceec
Create Date: 2016-02-27 15:31:51.448409

"""

# revision identifiers, used by Alembic.
revision = '90b5d9ef4ef2'
down_revision = 'df2ed3a8ceec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('row_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['row_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'row_id')
    ### end Alembic commands ###
