"""empty message

Revision ID: be89a6dd5769
Revises: b2d245b6760c
Create Date: 2016-03-03 13:45:14.937104

"""

# revision identifiers, used by Alembic.
revision = 'be89a6dd5769'
down_revision = 'b2d245b6760c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
